$(function(){
//LER SEMPRE QUE O USUÁRIO DIGITAR ALGO

	//DA ONDE QUE EU VOU LER ESSES DADOS? LÁ DO CAMPO PESQUISA DO MEU FORMULARIO, 
	//EU VOU PEGAR OQUE O USUÁRIO DIGITIU ATRAVEZ DO ID DO MEU INPUT.
	
	//COMO QUE EU VOU LER? EU VOU LER SEMPRE QUE O USUARIO PRECIONAR UMA TECLA ELE VAI LER OQUE O USUARIO DIGITA
	//keyup = SEMPRE QUE O USUARIO DIGITAR ELE VAI LER.
	$("#pesquisa").keyup(function(){ //RESUMINDO SEMPRE QUE ELE LER ALGUMA COISA DO TECLADO ELE VAI ENTRAR NESSA FUNÇÃO
		//SEMPRE QUE O KEYUP LER A TECLA ELE VAI ENTRAR NESSA FUNÇÃO
		//
		//SEMPRE QUE ELE LER OQUE O USUÁRIO DIGITAR ELE VAI ATRIBUIR PRA VARIAVEL "PESQUISA"
		var pesquisa = $(this).val();//(val = value) O this(este) é uma referência para o próprio objeto

		//AQUI EU VOU VERIFICAR SE A MINHA VARIAVEL PESQUISA POSSUI ALGO
		if(pesquisa != ''){

			var dados = {
				//ESSA MINHA VARIVEL DADOS VAI TER UMA PALAVRA QUE VAI RECEBER DA VARIVEL PESQUISA
				palavra : pesquisa
			}
			//ESSA PALAVRA EU VOU PASSAR ATRAVEZ DO METODO POST ENTÃO EU VOU PASSAR PRO ARQUIVO QUE DEVE PESQUISAR
			//ELE VAI PASSAR ESSES DADOS QUE ESTÃO NA VARIAVEL DADOS
			//ESSE ARQUIVO administrativo_pesquisa_usuario.php QUE VAI FICAR RESPONSAVEL DE BUSCAR OS DADOS NO BANCO DE DADOS
			$.post('administrativo/pesquisar/adm_busca_usuario.php', dados, function(retorna){
				//MOSTRAR OS DADOS OBTIDOS
				//ELE VAI MOSTRAR AONDE? ELE VAI MOSTRAR NUMA CLASSE, ESSA CLASSE É A CLASSE RESULTADO
				$(".resultado").html(retorna);//AQUI EU VOU RETORNAR OS ARQUIVOS QUE ELE TIVER PESQUISADO, ENTÃO TODOS OS DADOS QUE ELE
				//OBTER ELE VAI RETORNAR
			});
		}else{
				$(".resultado").html('');
		}
	});



});